"""Update livedb item field names

Peek Plugin Database Migration Script

Revision ID: 51086341adcd
Revises: 4740c2e8644a
Create Date: 2017-07-06 17:03:48.099045

"""

# revision identifiers, used by Alembic.
revision = '51086341adcd'
down_revision = '4740c2e8644a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LiveDbItem', sa.Column('displayValue', sa.String(), nullable=True), schema='pl_livedb')
    op.add_column('LiveDbItem', sa.Column('key', sa.String(), nullable=False), schema='pl_livedb')
    op.add_column('LiveDbItem', sa.Column('rawValue', sa.String(), nullable=True), schema='pl_livedb')
    op.drop_index('idx_LiveDbDKey_liveDbKey', table_name='LiveDbItem', schema='pl_livedb')
    op.create_index('idx_LiveDbDKey_liveDbKey', 'LiveDbItem', ['key'], unique=False, schema='pl_livedb')
    op.drop_column('LiveDbItem', 'value', schema='pl_livedb')
    op.drop_column('LiveDbItem', 'liveDbKey', schema='pl_livedb')
    op.drop_column('LiveDbItem', 'convertedValue', schema='pl_livedb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LiveDbItem', sa.Column('convertedValue', sa.VARCHAR(), autoincrement=False, nullable=True), schema='pl_livedb')
    op.add_column('LiveDbItem', sa.Column('liveDbKey', sa.VARCHAR(), autoincrement=False, nullable=False), schema='pl_livedb')
    op.add_column('LiveDbItem', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True), schema='pl_livedb')
    op.drop_index('idx_LiveDbDKey_liveDbKey', table_name='LiveDbItem', schema='pl_livedb')
    op.create_index('idx_LiveDbDKey_liveDbKey', 'LiveDbItem', ['liveDbKey'], unique=False, schema='pl_livedb')
    op.drop_column('LiveDbItem', 'rawValue', schema='pl_livedb')
    op.drop_column('LiveDbItem', 'key', schema='pl_livedb')
    op.drop_column('LiveDbItem', 'displayValue', schema='pl_livedb')
    # ### end Alembic commands ###