"""Added update queue table

Peek Plugin Database Migration Script

Revision ID: 62a2c58676e5
Revises: 19b2a8d326ad
Create Date: 2020-04-16 08:20:52.910427

"""

# revision identifiers, used by Alembic.
revision = '62a2c58676e5'
down_revision = '19b2a8d326ad'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LiveDbRawValueQueue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelSetKey', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('rawValue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'modelSetKey', 'key', 'rawValue'),
    schema='pl_livedb'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LiveDbRawValueQueue', schema='pl_livedb')
    # ### end Alembic commands ###